version: 2
updates:
- package-ecosystem: gomod
  directory: /go/
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: /python/
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: /rust/
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
